--	Microsoft SQL Server 2019 (RTM) - 15.0.2000.5 (X64)   
--	Sep 24 2019 13:48:23   Copyright (C) 2019 Microsoft Corporation  Developer Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 19043: ) 

--	PURPOSE : I try the project for car management in company : 사내 차량 관리 프로그램
CREATE DATABASE CAR_MANAGE_IN_COMPANY

--	CODE
CREATE TABLE	GROUP_CODE_TB(
	IDX				INT				IDENTITY
	,CODE			CHAR(5)			PRIMARY KEY
	,VALUE			VARCHAR(255)	NOT NULL
	,IS_USE			BIT				NOT NULL DEFAULT 'TRUE'
	,REG_DATE		DATETIME		DEFAULT GETDATE()
)
CREATE TABLE	CODE_TB(
	IDX				INT				IDENTITY
	,CODE			CHAR(5)			PRIMARY KEY
	,VALUE			VARCHAR(255)	NOT NULL
	,GRP_CODE		CHAR(5)			NOT NULL
	,IS_USE			BIT				NOT NULL DEFAULT 'TRUE'
	,REG_DATE		DATETIME		DEFAULT GETDATE()
	CONSTRAINT	FK_CODE_TO_GRP_CODE FOREIGN KEY (GRP_CODE) REFERENCES GROUP_CODE_TB (CODE)
)
--	회사에 속한 사용자들
CREATE TABLE USER_TB(
	IDX				INT				PRIMARY KEY	IDENTITY
	,ID				VARCHAR(50)		NOT NULL UNIQUE
	,PWD			VARCHAR(50)		NOT NULL
	,NAME			VARCHAR(50)		NOT NULL 
	,DEPT_CD		CHAR(5)			--	GD001
	,DEPT_POSITION	CHAR(5)			--	GD002
	,E_MAIL			VARCHAR(50)		UNIQUE
	,GENDER			CHAR(1)			CHECK	(GENDER IN ('F''M'))
	,BRITH_DAY		SMALLDATETIME
	,HOLD_AMT		MONEY			DEFAULT 0 CHECK(HOLD_AMT >= 0)
	,POST_NO		INT
	,ADDRESS		VARCHAR(200)
	,FAIL_CNT		TINYINT			NOT NULL DEFAULT 0
	,IS_USE			BIT				NOT NULL DEFAULT 'TRUE'
	,REG_DATE		DATETIME		DEFAULT GETDATE()
	,UPD_DATE		DATETIME
	CONSTRAINT	FK_DEPT_CD			FOREIGN KEY (DEPT_CD)			REFERENCES CODE_TB (CODE)
	,CONSTRAINT	FK_DEPT_POSITION	FOREIGN KEY (DEPT_POSITION)		REFERENCES CODE_TB (CODE)
)

CREATE TABLE CAR_INFO_TB(
	IDX				INT				PRIMARY KEY IDENTITY
	,CAR_NO			VARCHAR(20)		NOT NULL
	,CAR_NAME		VARCHAR(50)
	,VEHICLE_TYPE	CHAR(5)			--	GC100
	,CAR_SIZE		CHAR(5)			--	GC101
	,CAR_TYPE		CHAR(5)			--	GC102


	,IS_USE			BIT				NOT NULL DEFAULT 'TRUE'
	,REG_DATE		DATETIME		DEFAULT GETDATE()
	,UPD_DATE		DATETIME
	CONSTRAINT FK_VEHICLE_TYPE		FOREIGN KEY (VEHICLE_TYPE)		REFERENCES CODE_TB (CODE)
	,CONSTRAINT FK_CAR_SIZE			FOREIGN KEY (CAR_SIZE)			REFERENCES CODE_TB (CODE)
	,CONSTRAINT FK_CAR_TYPE			FOREIGN KEY (CAR_TYPE)			REFERENCES CODE_TB (CODE)
)

CREATE TABLE RESERVATION_INFO_TB(
	IDX				INT				PRIMARY KEY IDENTITY
	,USER_IDX		INT				FOREIGN KEY REFERENCES	USER_TB (IDX)	ON	UPDATE CASCADE
	,CAR_IDX		INT
	,IS_USE			BIT				NOT NULL DEFAULT 'TRUE'
	,STR_DATE		SMALLDATETIME
	,END_DATE		SMALLDATETIME
	,PURPOSE		VARCHAR(255)
	,REG_DATE		DATETIME		DEFAULT GETDATE()
	,REG_USER		VARCHAR(50)
	,UPD_DATE		DATETIME
	,UPD_USER		VARCHAR(50)

	,CONSTRAINT FK_CAR_IDX		FOREIGN KEY (CAR_IDX)	REFERENCES	CAR_INFO_TB (IDX)	ON	UPDATE CASCADE
)

-- DUMMY 입력 부분
INSERT INTO GROUP_CODE_TB(CODE, VALUE) VALUES('G0000', '미개발')
INSERT INTO GROUP_CODE_TB(CODE, VALUE) VALUES('GD001', '부서')
INSERT INTO GROUP_CODE_TB(CODE, VALUE) VALUES('GD002', '직위')
INSERT INTO GROUP_CODE_TB(CODE, VALUE) VALUES('GC100', '탈것 종류')
INSERT INTO GROUP_CODE_TB(CODE, VALUE) VALUES('GC101', '차량 크기')
INSERT INTO GROUP_CODE_TB(CODE, VALUE) VALUES('GC102', '차종')

INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('DA001', '경영', 'GD001')
INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('DA002', '영업', 'GD001')
INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('DA003', '개발', 'GD001')

INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('DB001', '경영', 'GD002')
INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('DB002', '영업', 'GD002')
INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('DB003', '개발', 'GD002')

INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('VT001', '사륜차', 'GC100')
INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('VT002', '이륜차', 'GC100')
INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('VT003', '원동기', 'GC100')

INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('CS001', '소형', 'GC101')
INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('CS002', '중형', 'GC101')
INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('CS003', '화물', 'GC101')
INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('CS100', '전기차', 'GC101')

INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('CT001', '라세티', 'GC102')
INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('CT002', '벤츠', 'GC102')
INSERT INTO CODE_TB(CODE, VALUE, GRP_CODE) VALUES('CT003', '마티즈', 'GC102')

INSERT INTO USER_TB(ID, PWD, NAME) VALUES('ADMIN', '1234', '관리자')

INSERT INTO CAR_INFO_TB(CAR_NO, CAR_NAME, VEHICLE_TYPE, CAR_SIZE, CAR_TYPE)
	VALUES('12가1234', '의미 중복 컬럼', 'VT001', 'CS002', 'CT001')

INSERT INTO RESERVATION_INFO_TB(USER_IDX, CAR_IDX, STR_DATE, END_DATE, REG_USER)
	VALUES(1, 1, GETDATE(), GETDATE()+7, '개발자')



